language: c

# This is the travis.yml Script for my Led_Analyzer Project

env:
  global:
    - secure: "cYO+77K4FIp5TXbGSn2QkVBnf+usTo4vtnkZ+Cqx/y2HadI/gzfIDq1JIX0Za9Ov7X7QIUYpelWFt1DkYGgjg0xzIChBDp7F3/6mRXUlnPIu3LcNVrY4toIkFy6LdygwanMpPMVloe+DNOTvAcq6pqiJnEFPDm/0QXq4Hq1EVKo="
    - PATH=/usr/mingw-w64-i686/bin:/usr/mingw-w64-x86_64/bin:/tmp/apache-ant-1.9.6/bin:${PATH}

before_install:
  - sudo dpkg --purge cmake cmake-doc cmake-data
  - curl -sL http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04/Release.key | sudo apt-key add -
  - echo "deb http://download.opensuse.org/repositories/home:/doc_bacardi/xUbuntu_12.04 ./" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get --assume-yes install cmake3 doxygen doxygen-gui graphviz make mingw-w64-mbs mingw64-wxwidgets python-pip python-virtualenv swig3
  - wget http://downloads.sourceforge.net/project/muhkuh/mbs/org/apache/ant/1.9.6/apache-ant-1.9.6-bin.tar.bz2 -O /tmp/apache-ant-1.9.6-bin.tar.bz2
  - tar --directory /tmp --extract --bzip2 --file /tmp/apache-ant-1.9.6-bin.tar.bz2
  - virtualenv ~/virtualenv/python2.7
  - source ~/virtualenv/python2.7/bin/activate
  - pip install -q requests


# This is the command to build the whole project and pack the results in a distributable form.
script:
  - unset CC
  - ./.build.sh


after_success:
  - python ivy/installer/deploy.py build/artifacts/artifacts_led_analyzer.xml build/artifacts/artifacts_coco_gui.xml

