Project LED Analyzer 
===================

Subhan Waizi + 
<swaizi@hilscher.com> + 

Build status: [![Build Status](https://travis-ci.org/muhkuh-sys/led_analyzer)](https://travis-ci.org/muhkuh-sys/led_analyzer)


[[About, About]]
== About   

This document describes the LED Analyzer project which uses TCS3472 Color Sensors for wavelength and brightness detection of light emitting diodes. 
The project is intended to be used in Hilscher's internal test environment and will test LEDs on manufactured printed circuit boards.
It provides functionality to be both used in an autonomous application and in Hilscher's muhkuh test frameworks. 


[[Hardware, Hardware]]
== Hardware

The hardware consists of a complete ftdi 2232h chip circuit including an eeprom for company specific descriptors. All availabe GPIO pins were used to provide 
16 I2C-Interfaces which were connected to 16 of AMS TCS3472 Color Sensors. Hardware is designed for use with light pipes. Make sure to use an intransparent case,
to reduce light noise produced by environmental lighting. An adequate case will also enable the sensor to distinguish between measurement of light emitting objects
and measurement of environmental light by evaluating their LUX levels. 


[[Software, Software]]
== Software 

* An interface to talk to the ftdi chips is provided by libusb v1.0.19 and libftdi v1.2. These libraries were used to write software based I2C for 16 seperate I2C-busses,
which are necessary due to the sensors' unchangable I2C-Address. These functions were made ready for use under LUA by wrapping them with swigwin v3.0.5.

* The lua scripts handle all color related functionality, including conversions between color spaces, displaying color values in various color spaces and validation of the device under test.
Each device under test will have its unique "test table" that contains entries for each LED on the board. This entry consists of a number which corresponds to the sensor number connected to the LED,
the wavelength of the LED, saturation of the LED and (optionally) an illuminance value, given in LUX. A tolerance value must be provided for each of these testing values. A LED under test will be 
marked as "OK" if the measured data of one sensor matches its "wanted data + tolerances"-entries in the "test table".

* The GUI Application called CoCo App will show all connected Led Analyzer Devices and their measured color data, including wavelength saturation and illuminance. Furthermore color sensor specific settings
like integration time and gain can be set up easily. The App displays the status of the sensors, giving various information in case any problems occur.
"Test Tables" for later use in an automated test environment (e.g. muhkuh test framwork) can be generated here. 


[[Documentation, Documentation]]
== Documentation

A code documentation will be generated along the cmake build process, if doxygen is installed. This documentation can be found in the build folder under 'doc' and contains both
html documentation and tex documentation files.





A detailled description of drivers, lua scripts and usage of the application will follow.





